# Conceptos y definiciones sobre matrices #

A continuación incluimos una recopilación de conceptos y definiciones sobre matrices que nos serán útiles posteriormente.

**Matriz cuadrada o de orden $n$**

Una matriz $A$ de $n \times m$ elementos, es una matriz cuadrada si el número de filas es igual al número columnas, es decir, ${\displaystyle n=m}$ y se dice, entonces, que la matriz es de orden $n$.

Las matrices cuadradas son las más utilizadas en álgebra.

$$ {\displaystyle A={\begin{pmatrix}a_{11}&a_{12}&a_{13}&\cdots &a_{1n}\\a_{21}&a_{22}&a_{23}&\cdots &a_{2n}\\a_{31}&a_{32}&a_{33}&\cdots &a_{3n}\\\vdots &\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&a_{n3}&\cdots &a_{nn}\\\end{pmatrix}}} $$

Sea $A$ una matriz con $m$ filas y $n$ columnas. La matriz traspuesta de $A$ se denota ${\displaystyle A^{t}}$ donde ${\displaystyle a^{t}_{ij}=a_{ji},\ 1\leq i\leq n,\ 1\leq j\leq m}$

Ejemplos:

In [1]:
import numpy as np

# Two matrices
m1 = np.array([[5, 10], [15, 20]])
print('m1=\n', m1)
print('m1.T=\n', m1.T)

m1=
 [[ 5 10]
 [15 20]]
m1.T=
 [[ 5 15]
 [10 20]]


In [2]:
m2 = np.array([[5, 25, 30, 34], [10, 35, 40, 42]])
print('m2=\n', m2)
print('m2.T=\n', m2.T)

m2=
 [[ 5 25 30 34]
 [10 35 40 42]]
m2.T=
 [[ 5 10]
 [25 35]
 [30 40]
 [34 42]]


**Propiedad involutiva**: Para toda matriz $A$, se tiene que: ${\displaystyle (A^{t})^{t}=A\,}$

In [3]:
print('m2.T.T=2\n', m2.T.T)
print('m2=\n', m2)

m2.T.T=2
 [[ 5 25 30 34]
 [10 35 40 42]]
m2=
 [[ 5 25 30 34]
 [10 35 40 42]]


**Propiedad Distributiva**: Sean $A$ y $B$ matrices reales del mismo orden y $c$ un número real, entonces:

$$ {\displaystyle (A+B)^{t}=A^{t}+B^{t}\,} $$

$$ {\displaystyle (c\,A)^{t}=c\,A^{t}}$$

In [4]:
print('m1=\n',m1)
print('(m1+m1).T=\n', (m1+m1).T)
print('m1.T+m1.T=\n', m1.T + m1.T)

m1=
 [[ 5 10]
 [15 20]]
(m1+m1).T=
 [[10 30]
 [20 40]]
m1.T+m1.T=
 [[10 30]
 [20 40]]


In [5]:
c = 3
print('c=', c)
print('(c*m1).T=\n', (c*m1).T)
print('c*m1.T=\n', c*m1.T)

c= 3
(c*m1).T=
 [[15 45]
 [30 60]]
c*m1.T=
 [[15 45]
 [30 60]]


**Producto matricial**: ${\displaystyle (AB)^{t}=B^{t}A^{t}\,}$

In [6]:
A = np.array([[5, 10], [15, 20]])
B = np.array([[25, 30], [35, 40]])
print('A=\n', A)
print('B=\n', B)
print('(A*B).T=\n', (A*B).T)
print('B.T*A.T=\n',B.T*A.T)

A=
 [[ 5 10]
 [15 20]]
B=
 [[25 30]
 [35 40]]
(A*B).T=
 [[125 525]
 [300 800]]
B.T*A.T=
 [[125 525]
 [300 800]]


Una matriz cuadrada $A$ es simétrica si coincide con su traspuesta: ${\displaystyle A^{t}=A\,}$

In [7]:
print('A=\n', A)
print('A.T=\n', A.T)

A=
 [[ 5 10]
 [15 20]]
A.T=
 [[ 5 15]
 [10 20]]


In [8]:
mat = np.array([[1, 3, 5], [3, 2, 4], [5, 4, 1]])
print('mat=\n',mat)
print('mat.T=\n',mat.T)

mat=
 [[1 3 5]
 [3 2 4]
 [5 4 1]]
mat.T=
 [[1 3 5]
 [3 2 4]
 [5 4 1]]


Una matriz hermítica es una matriz cuadrada con números complejos que tiene la característica de ser igual a su traspuesta conjugada: $A=A^*$

Observe el uso del caracter '*' para indicar la transpuesta conjugada.

In [9]:
g = np.matrix([1-2j, 3-4j])
print('g=\n', g)
# applying matrix.getH() method
gk = g.getH()
print('gk=\n', gk)


g=
 [[1.-2.j 3.-4.j]]
gk=
 [[1.+2.j]
 [3.+4.j]]


La suma de dos matrices simétricas es una matriz simétrica, pero el producto no siempre es simétrico. el producto de dos matrices es simétrico si y solo si dichas matrices cumplen la propiedad conmutativa de la multiplicación, es decir, si $AB = BA$.

In [10]:
A = np.array([[2,3,6],[3,4,5],[6,5,9]])
B = np.array([[1,2,-1],[2,1,3],[-1,3,0]])
print('A=\n', A)
print('B=\n', B)
print('A+B=\n', A+B)

A=
 [[2 3 6]
 [3 4 5]
 [6 5 9]]
B=
 [[ 1  2 -1]
 [ 2  1  3]
 [-1  3  0]]
A+B=
 [[3 5 5]
 [5 5 8]
 [5 8 9]]


In [11]:
# Sin embargo, la matriz producto no es simétrica en este caso.

print('A*B=\n', np.matmul(A,B))

A*B=
 [[ 2 25  7]
 [ 6 25  9]
 [ 7 44  9]]


In [12]:
# El operador '@' se puede utilizar también para la multiplicación matricial
print('A@B=\n', A@B)

A@B=
 [[ 2 25  7]
 [ 6 25  9]
 [ 7 44  9]]


**Matriz Triangular**

Una matriz triangular es un tipo especial de matriz cuadrada cuyos elementos por encima o por debajo de su diagonal principal o su diagonal secundaria son cero. 

Debido a que los sistemas de ecuaciones lineales con matrices triangulares son mucho más fáciles de resolver, las matrices triangulares son utilizadas en análisis numérico para resolver sistemas de ecuaciones lineales, calcular inversas y determinantes de matrices.

Una matriz cuadrada de orden n se dice que es triangular superior si es de la forma:

$${\displaystyle U=\left[{\begin{array}{ccccccc}u_{11}&u_{12}&u_{13}&.&.&.&u_{1n}\\0&u_{22}&u_{23}&.&.&.&u_{2n}\\0&0&u_{33}&.&.&.&u_{3n}\\.&.&..&.&.&.&.\\.&.&.&.&.&.&.\\.&.&.&.&.&.&.\\0&0&0&.&.&.&u_{nn}\\\end{array}}\right]}$$

Por otra parte, se dice que es una matriz triangular inferior si es de la forma:

$${\displaystyle L=\left[{\begin{array}{ccccccc}l_{11}&0&0&.&.&.&0\\l_{21}&l_{22}&0&.&.&.&0\\l_{31}&l_{32}&l_{33}&.&.&.&0\\.&.&.&.&.&.&.\\.&.&.&.&.&.&.\\.&.&.&.&.&.&.\\l_{n1}&l_{n2}&l_{n3}&.&.&.&l_{nn}\\\end{array}}\right]}$$

Se suelen emplear las letras $U$ y $L$, respectivamente, ya que $U$ es la inicial de upper triangular matrix y $L$ de lower triangular matrix, los nombres que reciben estas matrices en inglés.

Ejemplo: esta matriz es triangular superior:

$$ {\displaystyle \left[{\begin{array}{ccc}1&4&2\\0&3&4\\0&0&1\end{array}}\right]}$$

Y esta es triangular inferior:

$${\displaystyle \left[{\begin{array}{ccc}1&0&0\\2&8&0\\4&9&7\end{array}}\right]}$$

Y esta es triangular superior unitaria, ya que los elementos en su diagonal son 1:


$${\displaystyle \left[{\begin{array}{ccc}1&4&2&5&6\\0&1&4&8&-1\\0&0&1&4&3\\0&0&0&1&3\\0&0&0&0&1\\\end{array}}\right]}$$

La matriz triangular inferior unitaria es análoga.

**Propiedades**

El determinante de una matriz triangular es el producto de los elementos de la diagonal.

Los valores propios de una matriz triangular son los elementos de la diagonal principal.

La transpuesta de una matriz triangular superior es una matriz triangular inferior y viceversa.

In [13]:
M = np.array([[1, 3, 5, 3],  
     [0, 4, 6, 2],
     [0, 0, 2, 5],
     [0, 0, 0, 6]])
M.T

array([[1, 0, 0, 0],
       [3, 4, 0, 0],
       [5, 6, 2, 0],
       [3, 2, 5, 6]])

El producto de dos matrices triangulares superiores (inferiores) es una matriz triangular superior (inferior).

In [14]:
P = np.array([[1, 7, 5, 8],  
              [0, 4, 6, 4],
              [0, 0, 2, 5],
              [0, 0, 0, 6]])
P

array([[1, 7, 5, 8],
       [0, 4, 6, 4],
       [0, 0, 2, 5],
       [0, 0, 0, 6]])

In [15]:
M@P

array([[ 1, 19, 33, 63],
       [ 0, 16, 36, 58],
       [ 0,  0,  4, 40],
       [ 0,  0,  0, 36]])

Una matriz triangular es invertible si y solo si todos los elementos de la diagonal son no nulos. 

In [16]:
np.linalg.inv(M)

array([[ 1.        , -0.75      , -0.25      , -0.04166667],
       [ 0.        ,  0.25      , -0.75      ,  0.54166667],
       [ 0.        ,  0.        ,  0.5       , -0.41666667],
       [ 0.        ,  0.        ,  0.        ,  0.16666667]])

En este caso, la inversa de una matriz triangular superior (inferior) es otra matriz triangular superior (inferior).

In [17]:
# Si alguno de los elementos de la diagonal es nulo, la matriz es singular y 
# no es invertible

Q = np.array([[1, 7, 5, 8],  
              [0, 0, 6, 4],
              [0, 0, 2, 5],
              [0, 0, 0, 6]])
np.linalg.inv(Q)

LinAlgError: Singular matrix

Una matriz singular es una matriz cuadrada cuyo determinante es nulo (i.e., igual a cero). Una matriz singular no tiene matriz inversa. Por tanto, para evitar el error anterior debemos verificar previamente si el determinante de la matriz es diferente de cero, lo cual no se cumple en este caso.

In [ ]:
np.linalg.det(Q)

Una matriz es invertible si y sólo si su determinante es distinto de cero, es decir si no es una matriz singular. También se conocen como regulares, no degeneradas o no singulares. 

Si $A$ es una matriz invertible de orden $n$, entonces existe una matriz B de orden $n$ tal que: $A.B = B.A = I$. En este caso, $B$ es la matriz inversa de $A$, identificada por $A^{-1}$.



Una matriz diagonal es una matriz cuyos elementos fuera de la diagonal principal son todos cero; el término usualmente hace referencia a matrices cuadradas.

In [ ]:
Q = np.array([[1, 0, 0, 0],  
                 [0, 4, 0, 0],
                 [0, 0, 2, 0],
                 [0, 0, 0, 6]])
Q

In [ ]:
R = np.array([[6, 0, 0, 0],  
                 [0, 3, 0, 0],
                 [0, 0, 4, 0],
                 [0, 0, 0, 8]])
R

La suma de dos matrices diagonales $A$ y $B$ es otra matriz diagonal $C$ tal que $c_{i,i}=a_{i,i} + b_{i,i}$

In [ ]:
Q + R

El producto de dos matrices diagonales $A$ y $B$ es otra matriz diagonal $C$ tal que $c_{i,i}=a_{i,i} * b_{i,i}$

In [ ]:
Q * R

El determinante de una matriz diagonal es el producto de los elementos de su diagonal.

Los valores propios de una matriz diagonal los elementos de su diagonal.

La matriz identidad es una matriz cuadrada de orden $n$ en la cual todos los elementos de la diagonal principal son iguales a 1 y todos los demás elementos son iguales a 0. Se trata de un caso particular de matriz diagonal, y se representa por $I$.

También se puede escribir usando la notación delta de Kronecker:

$${\displaystyle I_{ij}=\delta _{ij}\,}$$

La matriz identidad cumple la propiedad de ser el elemento neutro del producto de matrices, por lo que, dado una matriz cualquiera $A_n$ se cumple que $A_n.I_n = A_n$ 

Una matriz ortogonal es una matriz cuadrada cuya matriz inversa coincide con su matriz traspuesta.

Sea $A$ una matriz cuadrada de orden $n$ por con entradas reales. Se dice que la matriz es ortogonal si:

$${\displaystyle A\cdot A^{\mathrm {T} }=I}$$

donde ${\displaystyle A^{\mathrm {T} }}$ representa la matriz traspuesta de $A$ e $I$ representa la matriz identidad.

**Matrices semejantes**

Dos matrices $A$ y $B$ de orden $n$ son semejantes si existe una matriz invertible $P$ de orden $n$ tal que:

$$P^{-1}AP = B$$

Con lo cual, la matriz $A$ se puede transformar en la matriz $B$ mediante $P$.

In [ ]:
# Consideremos las siguientes matrices:

B = np.array([[2, 1], [0, 1]])
A = np.array([[1, 3], [0, 2]])
P = np.array([[3, 0], [1, 1]])


In [ ]:
B

In [ ]:
P1 = np.linalg.inv(P)
P1@A@P

Las matrices semejantes comparten varias propiedades:

*	poseen el mismo rango,

*	el mismo determinante,

*	la misma traza,

*	los mismos valores propios (aunque los vectores propios, en general, serán distintos),

*	el mismo polinomio característico.



El **rango de una matriz** es el número máximo de columnas (ídem para filas) que son linealmente independientes. El rango fila y el rango columna siempre son iguales y es llamado simplemente rango de $A$. Comúnmente se expresa como $rg(A)$.

Si la matriz $A$ no depende de parámetros, puede resultar muy cómodo utilizar operaciones elementales de fila para conseguir una matriz equivalente $E$ escalonada (triangular superior). El rango de la matriz $A$ será simplemente el número de entradas principales de la matriz escalonada $E$, o lo que es lo mismo, el número de filas no nulas de la matriz escalonada $E$. 


In [ ]:

R = np.array([ [1, 3, -2, 0, 2, 0],
                [2, 6, -5, -2, 4, -3],
                [0, 0, 5, 10, 0, 15],
                [2, 6, 0, 8, 4, 8]])
R

In [ ]:
np.linalg.matrix_rank(R)

Observe que, aunque la matriz es de tamaño $4\times6$, el rango es 3 debido a que la fila 4 se puede obtener como combinación de las restantes.

La **traza de una matriz** $A$ de orden $n$ está definida como la suma de los elementos de la diagonal principal de $A$. Es decir,

$${\displaystyle \operatorname {tr} (A)=a_{11}+a_{22}+\dots +a_{nn}}$$

donde $a_{i,j}$ representa el elemento que está en la fila $i$-ésima y en la columna $j$-ésima de $A$. Para cualquier otra matriz, la traza es la suma de sus valores propios.

In [ ]:
A = np.array([[2, 25, 7], [6, 25, 9], [7, 44, 9]])
A

In [ ]:
np.trace(A)

**Valores y vectores propios**

Si $\lambda$ es un número y $v$ es un vector no nulo tal que $A.v = \lambda.v$, entonces se dice que $v$ es un vector propio de $A$ y que $\lambda$ es su valor propio asociado. El número $\lambda$ es un valor propio de $A$ si y sólo si $A − \lambda.I$ no es invertible, lo que sucede si y sólo si el polinomio característico de $A$, $p_A(\lambda) = 0$. $p_A(x)$ es un polinomio de grado $n$ con $n$ raíces complejas. Cada matriz cuadrada tiene exactamente $n$ valores propios complejos.
La ecuación 

$$A.v = \lambda.v $$

se denomina problema de valores propios, el cual produce una ecuación polinómica de orden $N_\lambda$ denominada polinomio característico de la matriz

$$p(\lambda)=det(A- \lambda.I)=0.$$

Esta ecuación tendrá distintas soluciones para $N_λ$, donde $1 ≤ N_λ ≤ N$. Se denomina espectro de $A$ al conjunto de soluciones formado por los valores propios.


Ejemplo: consideremos la matriz

$$A={\begin{bmatrix}\;0&1&-1\\\;1&1&\;0\\-1&0&\;1\end{bmatrix}}$$

Para computar los valores propios de $A$, se determina el polinomio característico:

$$p(x)=\det(A-xI)=\det {\begin{vmatrix}-x&1&-1\;\;\\\;\;1&1\!-\!x&0\\-1&0&1\!-\!x\end{vmatrix}}$$

$$=-x^{3}+2x^{2}+x-2 = - (x - 2)(x - 1)(x + 1)$$

por lo que, los valores propios de $A$ son 2, 1 y -1. 

## Bibliografía ##

* [Matriz cuadrada](https://es.wikipedia.org/wiki/Matriz_cuadrada)

* [Matriz transpuesta](https://es.wikipedia.org/wiki/Matriz_transpuesta)

* [Matriz triangular](https://es.wikipedia.org/wiki/Matriz_triangular)

* [Matriz simétrica](https://www.matricesydeterminantes.com/matrices/tipos-de-matrices/matriz-simetrica-ejemplos-y-propiedades/)

* [Multiplicación de matrices](https://es.wikipedia.org/wiki/Multiplicaci%C3%B3n_de_matrices#:~:text=El%20producto%20de%20dos%20matrices,es%20decir%2C%20AB%20%E2%89%A0%20BA.&text=La%20divisi%C3%B3n%20entre%20matrices%2C%20es,aplicable%20a%20las%20matrices%20invertibles.)

* [Symmetric Matrix](https://www.cuemath.com/algebra/symmetric-matrix/)

* [Numpy.linalg.inv](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html)

* [Matriz diagonal](https://es.wikipedia.org/wiki/Matriz_diagonal)

* [Delta de Kronecker](https://es.wikipedia.org/wiki/Delta_de_Kronecker)

* [Matriz invertible](https://es.wikipedia.org/wiki/Matriz_invertible)

* [Matriz semejante](https://es.wikipedia.org/wiki/Matriz_semejante)

* [Rango de una matriz](https://es.wikipedia.org/wiki/Rango_(%C3%A1lgebra_lineal)#Rango_de_una_matriz)

* [Traza (álgebra lineal)](https://es.wikipedia.org/wiki/Traza_(%C3%A1lgebra_lineal))

* [Descomposición en valores propios de una matriz](https://es.wikipedia.org/wiki/Descomposici%C3%B3n_en_valores_propios_de_una_matriz)

* [Vector, valor y espacio propios](https://es.wikipedia.org/wiki/Vector,_valor_y_espacio_propios)

* [Polinomio característico ](https://es.wikipedia.org/wiki/Polinomio_caracter%C3%ADstico)

