<center> <h1>Resolución de Sistemas de Ecuaciones Lineales</h1> </center>

En matemáticas, un sistema de ecuaciones lineales está formado por una o más ecuaciones lineales que involucran las mismas variables. Una solución a un sistema lineal es una asignación de valores a dichas variables de forma que todas las ecuaciones se satisfagan simultáneamente. La palabra "sistema" indica que las ecuaciones deben considerarse colectivamente, en lugar de individualmente.

En matemáticas, la teoría de los sistemas lineales es la base y una parte fundamental del álgebra lineal, materia que se utiliza en la mayor parte de las matemáticas modernas. Los algoritmos computacionales para resolver dichos sistemas son una parte importante del álgebra lineal numérica y juegan un papel destacado en la ingeniería, la física, la química, la informática y la economía. Por otra parte, un sistema de ecuaciones no lineales a menudo se puede aproximar mediante un sistema lineal, una técnica útil al hacer un modelo matemático o una simulación por computadora de un sistema relativamente complejo.


Ejemplo: a continuación podemos ver un sistema de tres ecuaciones con tres variables $x, y, z$.

$${\displaystyle {\begin{cases}3x+2y-z=1\\2x-2y+4z=-2\\-x+{\frac {1}{2}}y-z=0\end{cases}}}$$

Una solución a dicho sistema viene dada por el siguiente conjunto ordenado, que hace que las tres ecuaciones sean válidas.

$${\displaystyle (x,y,z)=(1,-2,-2),}$$


Los sistemas de ecuaciones lineales se pueden clasificar según el número de soluciones de los mismos: 

* Compatible determinado: cuando tiene una única solución, por lo que cada variable solo puede tomar un único valor.

* Compatible indeterminado: cuando tiene infinitas soluciones.

* Incompatible: cuando no existe solución.




En general, un sistema con $m$ ecuaciones lineales y $n$ incógnitas se puede escribir como:

$${\displaystyle \left\{{\begin{matrix}a_{11}x_{1}&+a_{12}x_{2}&+\dots &+a_{1n}x_{n}&=b_{1}\\a_{21}x_{1}&+a_{22}x_{2}&+\dots &+a_{2n}x_{n}&=b_{2}\\\dots &\dots &\dots &\dots &\dots \\a_{m1}x_{1}&+a_{m2}x_{2}&+\dots &+a_{mn}x_{n}&=b_{m}\end{matrix}}\right.}$$

Donde ${\displaystyle x_{1},\dots ,x_{n}}$ representan las incógnitas a determinar, los valores $a_{{ij}}$ son los coeficientes del sistema y 
${\displaystyle b_{1},\dots ,b_{m}}$ son los términos independientes. 

Dicho sistema se acostumbra representar como:

$${\displaystyle \mathbf {Ax} =\mathbf {b} }$$

donde $A$ es la matriz de los coeficientes, $x$ es el vector de las incognitas y $b$ es el vector correspondiente a los términos independientes.

Dado un sistema de ecuaciones lineales:

$${\displaystyle \left\{{\begin{array}{rcrcrcr}3\,x_{1}&+&2\,x_{2}&+&\,x_{3}&=&1\\2\,x_{1}&+&2\,x_{2}&+&4\,x_{3}&=&-2\\-\,x_{1}&+&{\frac {1}{2}}\,x_{2}&-&\,x_{3}&=&0\end{array}}\right.}$$

Es posible reescribir el sistema separando los coeficientes con notación matricial:

$${\displaystyle {\begin{pmatrix}3&2&1\\2&2&4\\-1&\frac{1}{2}&-1\end{pmatrix}}{\begin{pmatrix}x_{1}\\x_{2}\\x_{3}\end{pmatrix}}={\begin{pmatrix}1\\-2\\0\end{pmatrix}}}$$



La matriz ampliada o aumentada del sistema anterior se forma adjuntando el vector independiente como una columna más de la matriz de los coeficientes.

$${\displaystyle (A|B)=\left[{\begin{array}{ccc|c}3&2&1&1\\2&2&4&-2\\-1&\frac{1}{2}&-1&0\end{array}}\right].}$$

In [2]:
import numpy as np

A = np.array([[3,2,1],[2,2,4],[-1,0.5,-1]])
A

array([[ 3. ,  2. ,  1. ],
       [ 2. ,  2. ,  4. ],
       [-1. ,  0.5, -1. ]])

In [3]:
B = np.array([1,-2,0])
B

array([ 1, -2,  0])

In [5]:
# para denotar columna se usa uno (1) axis = 1

C = np.insert(A, A.shape[1], B, 1)
C

array([[ 3. ,  2. ,  1. ,  1. ],
       [ 2. ,  2. ,  4. , -2. ],
       [-1. ,  0.5, -1. ,  0. ]])

Si el rango de la matriz de coeficientes es igual al rango de la matriz ampliada y además igual al número de incógnitas, el sistema es compatible determinado (SCD).

$$Rango(A) = Rango(A^*) = n.º incógnita → SCD$$

Si el rango de la matriz de coeficientes es igual al rango de la matriz ampliada pero menor que el número de incógnitas, el sistema es compatible indeterminado (SCI).

$$Rango(A) = Rango(A^*) < n.º incógnita → SCI$$

Por último, si los rangos de las matrices de coeficientes y ampliada son distintos, el sistema es compatible indeterminado (SI).

$$Rang(A) < Rang(A^*)  → SI$$

In [7]:
np.linalg.matrix_rank(A)

3

In [8]:
np.linalg.matrix_rank(C)

3

En este ejemplo, el sistema es compatible determinado

A continuación se exponen los siguientes tópicos:

* [Revisión de Conceptos sobre matrices ](https://github.com/andressotov/analisis_numerico/blob/main/Conceptos%20sobre%20matrices.ipynb).

* [Método de Gauss](https://github.com/andressotov/analisis_numerico/blob/main/Metodo_Eliminacion_Gauss.ipynb).

* [Descomposición LU](https://github.com/andressotov/analisis_numerico/blob/main/Factorizaci%C3%B3n%20LU.ipynb).

* [Descomposición QR](https://github.com/andressotov/analisis_numerico/blob/main/Factorizaci%C3%B3n%20QR.ipynb).

* [Descomposición Cholesky](https://github.com/andressotov/analisis_numerico/blob/main/Factorizaci%C3%B3n%20de%20Cholesky.ipynb).

* [Descomposición en valores singulares SVD](https://github.com/andressotov/analisis_numerico/blob/main/Factorizaci%C3%B3n%20en%20Valores%20Singulares.ipynb).


<center> <h3>Bibliografía</h3> </center>

* [System of linear equations](https://en.wikipedia.org/wiki/System_of_linear_equations)

* [Sistema de ecuaciones lineales](https://es.wikipedia.org/wiki/Sistema_de_ecuaciones_lineales)

* [Augmented matrix](https://en.wikipedia.org/wiki/Augmented_matrix)

* [Matriz aumentada](https://es.wikipedia.org/wiki/Matriz_aumentada)

* [Teorema de Rouché Frobenius](https://www.problemasyecuaciones.com/matrices/teorema-Rouche-Frobenius-enunciado-ejemplos-aplicacion-sistemas-ecuaciones-lineales-matrices.html)

* [Indeterminate system](https://en.wikipedia.org/wiki/Indeterminate_system#:~:text=In%20linear%20systems%2C%20indeterminacy%20occurs,rank%20of%20the%20coefficient%20matrix.)

* [Teorema de Rouché–Frobenius](https://es.wikipedia.org/wiki/Teorema_de_Rouch%C3%A9%E2%80%93Frobenius)

* [Rouché–Capelli theorem](https://en.wikipedia.org/wiki/Rouch%C3%A9%E2%80%93Capelli_theorem)

* [Sistemas de ecuaciones lineales](https://www.ieszaframagon.com/matematicas/matematicas2/algebra/6_sistemas_de_ecuaciones_lineales.html)